import { Language } from '../types';

const translations: Record<Language, Record<string, string>> = {
  [Language.EN]: {
    'appTitle': 'Aura Smart Guidance',
    'passenger': 'Passenger',
    'driver': 'Driver',
    'caregiver': 'Caregiver',
    'destination': 'Destination',
    'eta': 'ETA',
    'minutes': 'minutes',
    'driverInfo': "Driver's Info",
    'routeInfo': 'Route Info',
    'auraResponse': "Aura's Response",
    'askAura': 'Ask Aura...',
    'send': 'Send',
    'sosEmergency': 'SOS EMERGENCY',
    'listening': 'Listening...',
    'processing': 'Processing...',
    'error': 'Error. Try again.',
    'tapToSpeak': 'Tap to Speak',
    'micPermissionNeeded': 'Mic permission needed',
    'micPermissionInstructions': "Microphone access denied. Please click the lock icon in your browser's address bar to enable it.",
    'accessibilitySettings': 'Accessibility Settings',
    'language': 'Language',
    'largeFont': 'Large Font',
    'voiceOutput': 'Voice Output',
    'voiceSpeed': 'Voice Speed',
    'hapticFeedback': 'Haptic Feedback',
    'signLanguage': 'Sign Language',
    'assistanceNeeds': 'Assistance Needs',
    'instructions': 'Instructions',
    'emergencyAlert': 'EMERGENCY ALERT',
    'remoteMonitoring': 'Remote Monitoring',
    'notifications': 'Notifications',
    'liveCameraFeed': 'Live Camera Feed',
    'newRouteSuggested': 'New Route Suggestion',
    'accept': 'Accept',
    'decline': 'Decline',
    'currentStatus': 'Current Status',
    'inProgress': 'In Progress',
    'finished': 'Finished',
    'tripProgress': 'Trip Progress',
    'emergencyConfirmed': 'Emergency activated. I have notified your caregiver and driver.',
    'routeAccepted': 'Okay, taking the new route.',
    'routeDeclined': 'Okay, staying on the current route.',
    'notificationPreferences': 'Notification Preferences',
    'rideStartEnd': 'Ride Start/End',
    'etaUpdates': 'ETA Updates',
    'emergencyAlerts': 'Emergency Alerts',
  },
  [Language.FR]: {
    'appTitle': 'Aura Guidage Intelligent',
    'passenger': 'Passager',
    'driver': 'Conducteur',
    'caregiver': 'Aidant',
    'destination': 'Destination',
    'eta': 'ETA',
    'minutes': 'minutes',
    'driverInfo': "Infos Conducteur",
    'routeInfo': "Infos Itinéraire",
    'auraResponse': "Réponse d'Aura",
    'askAura': 'Demandez à Aura...',
    'send': 'Envoyer',
    'sosEmergency': 'SOS URGENCE',
    'listening': 'Écoute...',
    'processing': 'Traitement...',
    'error': 'Erreur. Réessayez.',
    'tapToSpeak': 'Appuyez pour parler',
    'micPermissionNeeded': 'Permission micro requise',
    'micPermissionInstructions': "Accès au microphone refusé. Veuillez cliquer sur l'icône de cadenas dans la barre d'adresse de votre navigateur pour l'activer.",
    'accessibilitySettings': "Paramètres d'accessibilité",
    'language': 'Langue',
    'largeFont': 'Grande Police',
    'voiceOutput': 'Sortie Vocale',
    'voiceSpeed': 'Vitesse Vocale',
    'hapticFeedback': 'Retour Haptique',
    'signLanguage': 'Langue des Signes',
    'assistanceNeeds': "Besoins d'assistance",
    'instructions': 'Instructions',
    'emergencyAlert': "ALERTE D'URGENCE",
    'remoteMonitoring': 'Surveillance à Distance',
    'notifications': 'Notifications',
    'liveCameraFeed': 'Flux Caméra en Direct',
    'newRouteSuggested': 'Nouvel Itinéraire Suggéré',
    'accept': 'Accepter',
    'decline': 'Refuser',
    'currentStatus': 'Statut Actuel',
    'inProgress': 'En Cours',
    'finished': 'Terminé',
    'tripProgress': 'Progression du Trajet',
    'emergencyConfirmed': "Urgence activée. J'ai prévenu votre aidant et le conducteur.",
    'routeAccepted': "D'accord, nous prenons le nouvel itinéraire.",
    'routeDeclined': "D'accord, nous restons sur l'itinéraire actuel.",
    'notificationPreferences': 'Préférences de notification',
    'rideStartEnd': 'Début/Fin de trajet',
    'etaUpdates': 'Mises à jour ETA',
    'emergencyAlerts': "Alertes d'urgence",
  },
  [Language.TA]: {
    'appTitle': 'ஆரா ஸ்மார்ட் வழிகாட்டி',
    'passenger': 'பயணி',
    'driver': 'ஓட்டுநர்',
    'caregiver': 'பராமரிப்பாளர்',
    'destination': 'இலக்கு',
    'eta': 'ETA',
    'minutes': 'நிமிடங்கள்',
    'driverInfo': "ஓட்டுநர் தகவல்",
    'routeInfo': 'பாதை தகவல்',
    'auraResponse': "ஆராவின் பதில்",
    'askAura': 'ஆராவிடம் கேளுங்கள்...',
    'send': 'அனுப்பு',
    'sosEmergency': 'அவசர உதவி',
    'listening': 'கேட்கிறது...',
    'processing': 'செயலாக்கப்படுகிறது...',
    'error': 'பிழை. மீண்டும் முயற்சிக்கவும்.',
    'tapToSpeak': 'பேச தட்டவும்',
    'micPermissionNeeded': 'மைக் அனுமதி தேவை',
    'micPermissionInstructions': 'மைக்ரோஃபோன் அணுகல் மறுக்கப்பட்டது. அதை இயக்க உங்கள் உலாவியின் முகவரிப் பட்டியில் உள்ள பூட்டு ஐகானைக் கிளிக் செய்யவும்.',
    'accessibilitySettings': 'அணுகல் அமைப்புகள்',
    'language': 'மொழி',
    'largeFont': 'பெரிய எழுத்து',
    'voiceOutput': 'குரல் வெளியீடு',
    'voiceSpeed': 'குரல் வேகம்',
    'hapticFeedback': 'ஹேப்டிக் பின்னூட்டம்',
    'signLanguage': 'சைகை மொழி',
    'assistanceNeeds': 'உதவி தேவைகள்',
    'instructions': 'வழிமுறைகள்',
    'emergencyAlert': 'அவசர எச்சரிக்கை',
    'remoteMonitoring': 'தொலை கண்காணிப்பு',
    'notifications': 'அறிவிப்புகள்',
    'liveCameraFeed': 'நேரடி கேமரா ஊட்டம்',
    'newRouteSuggested': 'புதிய பாதை பரிந்துரை',
    'accept': 'ஏற்கவும்',
    'decline': 'நிராகரிக்கவும்',
    'currentStatus': 'தற்போதைய நிலை',
    'inProgress': 'செயலில்',
    'finished': 'முடிந்தது',
    'tripProgress': 'பயண முன்னேற்றம்',
    'emergencyConfirmed': 'அவசரம் செயல்படுத்தப்பட்டது. உங்கள் பராமரிப்பாளர் மற்றும் ஓட்டுநருக்கு அறிவித்துள்ளேன்.',
    'routeAccepted': 'சரி, புதிய வழியில் செல்கிறோம்.',
    'routeDeclined': 'சரி, தற்போதைய வழியிலேயே தொடர்கிறோம்.',
    'notificationPreferences': 'அறிவிப்பு விருப்பத்தேர்வுகள்',
    'rideStartEnd': 'பயண ஆரம்பம்/முடிவு',
    'etaUpdates': 'ETA புதுப்பிப்புகள்',
    'emergencyAlerts': 'அவசர எச்சரிக்கைகள்',
  },
};

export const l = (lang: Language) => (key: string): string => {
  return translations[lang][key] || key;
};